import Foundation
import SwiftUI

class ProductStore: ObservableObject {
    @Published var categories: [Category] = []
    @Published var searchText: String = ""

    var filteredCategories: [Category] {
        if searchText.isEmpty { return categories }
        return categories.compactMap { cat in
            let filtered = cat.products.filter {
                $0.name.localizedCaseInsensitiveContains(searchText) ||
                $0.nameEN.localizedCaseInsensitiveContains(searchText) ||
                $0.description.localizedCaseInsensitiveContains(searchText) ||
                $0.descriptionEN.localizedCaseInsensitiveContains(searchText)
            }
            return filtered.isEmpty ? nil : Category(
                id: cat.id, name: cat.name, nameEN: cat.nameEN,
                icon: cat.icon, colorHex: cat.colorHex, products: filtered,
                imageName: cat.imageName
            )
        }
    }

    init() {
        loadProducts()
    }

    private func loadProducts() {

        // MARK: - Krill Yağı / Krill Oil
        let krillOil = Category(
            id: "krill",
            name: "Krill Yağı",
            nameEN: "Krill Oil",
            icon: "🐟",
            colorHex: "1B6CA8",
            products: [
                Product(id: "k1",
                        name: "NutraMedica Krill Complex",
                        nameEN: "NutraMedica Krill Complex",
                        description: "Omega-3, fosfolipid ve astaksantin kompleksi",
                        descriptionEN: "Omega-3, phospholipid and astaxanthin complex",
                        details: "Fosfolipid formunda omega-3, astaksantin antioksidanı ve kolin içeren kapsamlı krill kompleksi. Kalp, beyin ve eklem sağlığını destekler.",
                        detailsEN: "Comprehensive krill complex with omega-3 in phospholipid form, astaxanthin antioxidant and choline. Supports heart, brain and joint health.",
                        unit: "30 Kapsül / 30 Capsules",
                        categoryId: "krill", isAvailable: true,
                        imageSystemName: "drop.fill",
                        imageName: "krill_complex"),
                Product(id: "k2",
                        name: "Nutramedica Krill Oil 750 mg",
                        nameEN: "Nutramedica Krill Oil 750 mg",
                        description: "Saf krill yağı — yüksek emilimli omega-3",
                        descriptionEN: "Pure krill oil — high-absorption omega-3",
                        details: "Her kapsülde 750mg saf Antarktika krill yağı içerir. Fosfolipid yapısı sayesinde balık yağından daha iyi emilir. Antiinflamatuar ve kalp dostu formül.",
                        detailsEN: "Contains 750mg pure Antarctic krill oil per capsule. Absorbed better than fish oil thanks to its phospholipid structure. Anti-inflammatory and heart-friendly formula.",
                        unit: "30 Kapsül / 30 Capsules",
                        categoryId: "krill", isAvailable: true,
                        imageSystemName: "drop.fill",
                        imageName: "krill_oil_30"),
                Product(id: "k3",
                        name: "Nutramedica Krill Oil 750 mg",
                        nameEN: "Nutramedica Krill Oil 750 mg",
                        description: "Saf krill yağı — ekonomik büyük paket",
                        descriptionEN: "Pure krill oil — economical large pack",
                        details: "Her kapsülde 750mg saf Antarktika krill yağı içerir. Fosfolipid yapısı sayesinde balık yağından daha iyi emilir. Antiinflamatuar ve kalp dostu formül.",
                        detailsEN: "Contains 750mg pure Antarctic krill oil per capsule. Absorbed better than fish oil thanks to its phospholipid structure. Anti-inflammatory and heart-friendly formula.",
                        unit: "60 Kapsül / 60 Capsules",
                        categoryId: "krill", isAvailable: true,
                        imageSystemName: "drop.fill",
                        imageName: "krill_oil_60"),
                Product(id: "k4",
                        name: "Nutramedica Krill Kidz Liquid",
                        nameEN: "Nutramedica Krill Kidz Liquid",
                        description: "Çocuklar için sıvı krill yağı",
                        descriptionEN: "Liquid krill oil for children",
                        details: "Çocuklar için özel formüle edilmiş sıvı krill yağı. Beyin gelişimini, konsantrasyonu ve bağışıklık sistemini destekler. Kolay kullanım için sıvı formda.",
                        detailsEN: "Liquid krill oil specially formulated for children. Supports brain development, concentration and the immune system. In liquid form for easy use.",
                        unit: "150 ml / 5 fl oz",
                        categoryId: "krill", isAvailable: true,
                        imageSystemName: "drop.fill",
                        imageName: "krill_kidz"),
            ],
            imageName: "krill_complex"
        )

        // MARK: - Vitaminler / Vitamins
        let vitamins = Category(
            id: "vitamins",
            name: "Vitaminler",
            nameEN: "Vitamins",
            icon: "💊",
            colorHex: "F5A623",
            products: [
                Product(id: "v1",
                        name: "NutraMedica MultiMix B",
                        nameEN: "NutraMedica MultiMix B",
                        description: "Tüm B grubu vitaminleri tek formülde",
                        descriptionEN: "All B-group vitamins in one formula",
                        details: "B1, B2, B3, B5, B6, B7, B9 ve B12 vitaminlerini içeren kapsamlı B kompleks formülü. Enerji metabolizması, sinir sistemi ve hücre sağlığını destekler.",
                        detailsEN: "Comprehensive B complex formula containing vitamins B1, B2, B3, B5, B6, B7, B9 and B12. Supports energy metabolism, nervous system and cell health.",
                        unit: "30 Kapsül / 30 Capsules",
                        categoryId: "vitamins", isAvailable: true, imageSystemName: "pill.fill"),
                Product(id: "v2",
                        name: "NutraMedica MultiMix B",
                        nameEN: "NutraMedica MultiMix B",
                        description: "Tüm B grubu vitaminleri — ekonomik paket",
                        descriptionEN: "All B-group vitamins — economical pack",
                        details: "B1, B2, B3, B5, B6, B7, B9 ve B12 vitaminlerini içeren kapsamlı B kompleks formülü. Enerji metabolizması, sinir sistemi ve hücre sağlığını destekler.",
                        detailsEN: "Comprehensive B complex formula containing vitamins B1, B2, B3, B5, B6, B7, B9 and B12. Supports energy metabolism, nervous system and cell health.",
                        unit: "60 Kapsül / 60 Capsules",
                        categoryId: "vitamins", isAvailable: true, imageSystemName: "pill.fill"),
                Product(id: "v3",
                        name: "NutraMedica MgComplex + D3&K2",
                        nameEN: "NutraMedica MgComplex + D3&K2",
                        description: "Magnezyum, D3 ve K2 vitamini kombinasyonu",
                        descriptionEN: "Magnesium, D3 and K2 vitamin combination",
                        details: "Yüksek emilimli magnezyum bisglisinat ile D3 ve K2 vitaminlerinin sinerjistik kombinasyonu. Kemik sağlığı, kas fonksiyonu ve kardiyovasküler sistemi destekler.",
                        detailsEN: "Synergistic combination of highly absorbable magnesium bisglycinate with D3 and K2 vitamins. Supports bone health, muscle function and cardiovascular system.",
                        unit: "60 Kapsül / 60 Capsules",
                        categoryId: "vitamins", isAvailable: true, imageSystemName: "capsule.fill"),
                Product(id: "v4",
                        name: "NutraVieX C VIT1000 Extra",
                        nameEN: "NutraVieX C VIT1000 Extra",
                        description: "1000mg C vitamini — tablet form",
                        descriptionEN: "1000mg Vitamin C — tablet form",
                        details: "Güçlü antioksidan koruması için 1000mg C vitamini içerir. Bağışıklık sistemini güçlendirir, demir emilimini artırır ve hücre yenilenmesini destekler.",
                        detailsEN: "Contains 1000mg Vitamin C for powerful antioxidant protection. Strengthens the immune system, increases iron absorption and supports cell renewal.",
                        unit: "Tablet",
                        categoryId: "vitamins", isAvailable: true, imageSystemName: "pill.fill"),
                Product(id: "v5",
                        name: "NutraVieX C VIT1000 Extra",
                        nameEN: "NutraVieX C VIT1000 Extra",
                        description: "1000mg C vitamini — efervesan form",
                        descriptionEN: "1000mg Vitamin C — effervescent form",
                        details: "Suda çözünen efervesan formatta 1000mg C vitamini. Hızlı emilim sağlar. Bağışıklık sistemini destekler ve enerji seviyelerini artırır. Lezzetli portakal aromalı.",
                        detailsEN: "1000mg Vitamin C in water-soluble effervescent form. Provides rapid absorption. Supports the immune system and boosts energy levels. Delicious orange flavour.",
                        unit: "Efervesan Tablet / Effervescent Tablet",
                        categoryId: "vitamins", isAvailable: true, imageSystemName: "bubbles.and.sparkles.fill"),
                Product(id: "v6",
                        name: "Nutramedica D3 All Spray",
                        nameEN: "Nutramedica D3 All Spray",
                        description: "Pratik D3 vitamini oral sprey",
                        descriptionEN: "Convenient Vitamin D3 oral spray",
                        details: "Yetişkinler için 1000 IU D3 vitamini içeren oral sprey. Dil altına uygulanarak hızlı emilim sağlar. Kemik sağlığı, bağışıklık ve ruh hali için önerilir.",
                        detailsEN: "Oral spray containing 1000 IU Vitamin D3 for adults. Applied under the tongue for rapid absorption. Recommended for bone health, immunity and mood.",
                        unit: "1000 IU Sprey / Spray",
                        categoryId: "vitamins", isAvailable: true, imageSystemName: "drop.fill"),
                Product(id: "v7",
                        name: "Nutramedica D3 Kidz Spray",
                        nameEN: "Nutramedica D3 Kidz Spray",
                        description: "Çocuklar için D3 vitamini oral sprey",
                        descriptionEN: "Vitamin D3 oral spray for children",
                        details: "Bebekler ve çocuklar için 400 IU D3 vitamini içeren oral sprey. Kemik ve diş gelişimini, bağışıklık sistemini destekler. Alkol içermez, çocuklar için güvenli formül.",
                        detailsEN: "Oral spray containing 400 IU Vitamin D3 for infants and children. Supports bone and dental development and the immune system. Alcohol-free, safe formula for children.",
                        unit: "400 IU Çocuk Spreyi / Kids Spray",
                        categoryId: "vitamins", isAvailable: true, imageSystemName: "drop.fill"),
            ],
            imageName: "vitamins_category"
        )

        // MARK: - Bağışıklık Sistemi / Immune System
        let immune = Category(
            id: "immune",
            name: "Bağışıklık Sistemi",
            nameEN: "Immune System",
            icon: "🛡️",
            colorHex: "27AE60",
            products: [
                Product(id: "i1",
                        name: "NutraVieX Sambucus Complex",
                        nameEN: "NutraVieX Sambucus Complex",
                        description: "Mürver kompleksi — efervesan form",
                        descriptionEN: "Elderberry complex — effervescent form",
                        details: "Sambucus nigra (mürver) ekstresi, C vitamini ve çinko içeren efervesan formül. Bağışıklık sistemini güçlendirir, soğuk algınlığı ve grip semptomlarına karşı etkilidir.",
                        detailsEN: "Effervescent formula containing Sambucus nigra (elderberry) extract, Vitamin C and zinc. Strengthens the immune system and is effective against cold and flu symptoms.",
                        unit: "Efervesan Tablet / Effervescent Tablet",
                        categoryId: "immune", isAvailable: true, imageSystemName: "shield.fill"),
                Product(id: "i2",
                        name: "NutraVieX Plus Umckaloabo-Sambucus",
                        nameEN: "NutraVieX Plus Umckaloabo-Sambucus",
                        description: "Pelargonyum ve mürver — efervesan form",
                        descriptionEN: "Pelargonium and elderberry — effervescent form",
                        details: "Umckaloabo (Pelargonium sidoides) ve Sambucus nigra ekstrelerinin güçlü kombinasyonu. Üst solunum yolu enfeksiyonlarına karşı doğal destek. Efervesan form.",
                        detailsEN: "Powerful combination of Umckaloabo (Pelargonium sidoides) and Sambucus nigra extracts. Natural support against upper respiratory tract infections. Effervescent form.",
                        unit: "Efervesan Tablet / Effervescent Tablet",
                        categoryId: "immune", isAvailable: true, imageSystemName: "shield.fill"),
                Product(id: "i3",
                        name: "Nutraviex Kidz Umckaloabo-Sambucus",
                        nameEN: "Nutraviex Kidz Umckaloabo-Sambucus",
                        description: "Çocuklar için bağışıklık şurubu",
                        descriptionEN: "Immune syrup for children",
                        details: "Çocuklar için özel formüle edilmiş Umckaloabo ve Sambucus içeren şurup. Üst solunum yolu sağlığını destekler, bağışıklık sistemini güçlendirir. Lezzetli çilek aromalı.",
                        detailsEN: "Syrup containing Umckaloabo and Sambucus specially formulated for children. Supports upper respiratory health and strengthens the immune system. Delicious strawberry flavour.",
                        unit: "Şurup / Syrup",
                        categoryId: "immune", isAvailable: true, imageSystemName: "cross.case.fill"),
                Product(id: "i4",
                        name: "NutraVieX Plus Umckaloabo-Sambucus",
                        nameEN: "NutraVieX Plus Umckaloabo-Sambucus",
                        description: "Pelargonyum ve mürver — tablet form",
                        descriptionEN: "Pelargonium and elderberry — tablet form",
                        details: "Umckaloabo (Pelargonium sidoides) ve Sambucus nigra ekstrelerinin güçlü kombinasyonu. Üst solunum yolu enfeksiyonlarına karşı doğal destek. Tablet form.",
                        detailsEN: "Powerful combination of Umckaloabo (Pelargonium sidoides) and Sambucus nigra extracts. Natural support against upper respiratory tract infections. Tablet form.",
                        unit: "Tablet",
                        categoryId: "immune", isAvailable: true, imageSystemName: "shield.fill"),
                Product(id: "i5",
                        name: "NutraVieX Plus Umckaloabo-Sambucus",
                        nameEN: "NutraVieX Plus Umckaloabo-Sambucus",
                        description: "Pelargonyum ve mürver — pastil form",
                        descriptionEN: "Pelargonium and elderberry — lozenge form",
                        details: "Umckaloabo (Pelargonium sidoides) ve Sambucus nigra ekstrelerinin güçlü kombinasyonu. Üst solunum yolu sağlığını destekler. Kullanımı kolay pastil form.",
                        detailsEN: "Powerful combination of Umckaloabo (Pelargonium sidoides) and Sambucus nigra extracts. Supports upper respiratory health. Easy-to-use lozenge form.",
                        unit: "Pastil / Lozenge",
                        categoryId: "immune", isAvailable: true, imageSystemName: "shield.fill"),
            ],
            imageName: "immune_category"
        )

        // MARK: - Adli Tıp Ürünleri / Forensic Products
        let forensic = Category(
            id: "forensic",
            name: "Adli Tıp Ürünleri",
            nameEN: "Forensic Products",
            icon: "🔬",
            colorHex: "5D6D7E",
            products: [
                Product(id: "f1",
                        name: "De-Tox Tubes A",
                        nameEN: "De-Tox Tubes A",
                        description: "Adli toksikoloji örnek toplama tüpü — Tip A",
                        descriptionEN: "Forensic toxicology sample collection tube — Type A",
                        details: "Adli toksikoloji analizleri için özel formüle edilmiş örnek toplama ve saklama tüpü. Laboratuvar ve adli bilimciler için profesyonel çözüm.",
                        detailsEN: "Sample collection and storage tube specially formulated for forensic toxicology analyses. Professional solution for laboratories and forensic scientists.",
                        unit: "Paket / Pack",
                        categoryId: "forensic", isAvailable: true, imageSystemName: "testtube.2"),
                Product(id: "f2",
                        name: "De-Tox Tubes B",
                        nameEN: "De-Tox Tubes B",
                        description: "Adli toksikoloji örnek toplama tüpü — Tip B",
                        descriptionEN: "Forensic toxicology sample collection tube — Type B",
                        details: "Adli toksikoloji analizleri için özel formüle edilmiş örnek toplama ve saklama tüpü. Laboratuvar ve adli bilimciler için profesyonel çözüm.",
                        detailsEN: "Sample collection and storage tube specially formulated for forensic toxicology analyses. Professional solution for laboratories and forensic scientists.",
                        unit: "Paket / Pack",
                        categoryId: "forensic", isAvailable: true, imageSystemName: "testtube.2"),
                Product(id: "f3",
                        name: "HemaFlx",
                        nameEN: "HemaFlx",
                        description: "Kan örneği stabilizasyon çözümü",
                        descriptionEN: "Blood sample stabilisation solution",
                        details: "Kan örneklerinin toplanması, saklanması ve analizinde kullanılan stabilizasyon çözümü. Adli tıp laboratuvarları için tasarlanmıştır.",
                        detailsEN: "Stabilisation solution used in the collection, storage and analysis of blood samples. Designed for forensic medicine laboratories.",
                        unit: "Paket / Pack",
                        categoryId: "forensic", isAvailable: true, imageSystemName: "drop.fill"),
                Product(id: "f4",
                        name: "OraFlx",
                        nameEN: "OraFlx",
                        description: "Oral sıvı örnek toplama sistemi",
                        descriptionEN: "Oral fluid sample collection system",
                        details: "Tükürük/oral sıvı örneklerinin toplanması ve stabilizasyonu için geliştirilmiş sistem. Non-invazif ve kullanımı kolay format.",
                        detailsEN: "System developed for collection and stabilisation of saliva/oral fluid samples. Non-invasive and easy-to-use format.",
                        unit: "Paket / Pack",
                        categoryId: "forensic", isAvailable: true, imageSystemName: "cross.case.fill"),
                Product(id: "f5",
                        name: "SeraFlx LCMSMS",
                        nameEN: "SeraFlx LCMSMS",
                        description: "Serum matrisi LC-MS/MS analizi için",
                        descriptionEN: "Serum matrix for LC-MS/MS analysis",
                        details: "LC-MS/MS bazlı adli toksikoloji analizleri için optimize edilmiş serum matrisi referans çözümü. Yüksek hassasiyetli analizler için tasarlanmıştır.",
                        detailsEN: "Serum matrix reference solution optimised for LC-MS/MS based forensic toxicology analyses. Designed for high-sensitivity analyses.",
                        unit: "Paket / Pack",
                        categoryId: "forensic", isAvailable: true, imageSystemName: "flask.fill"),
                Product(id: "f6",
                        name: "SeraFlx Biomatrix",
                        nameEN: "SeraFlx Biomatrix",
                        description: "Biyomatrix serum referans çözümü",
                        descriptionEN: "Biomatrix serum reference solution",
                        details: "Adli toksikoloji laboratuvarları için biyomatrix bazlı serum referans çözümü. Kalibrasyon ve kalite kontrol amaçlı kullanılır.",
                        detailsEN: "Biomatrix-based serum reference solution for forensic toxicology laboratories. Used for calibration and quality control purposes.",
                        unit: "Paket / Pack",
                        categoryId: "forensic", isAvailable: true, imageSystemName: "flask.fill"),
                Product(id: "f7",
                        name: "Surine E Control",
                        nameEN: "Surine E Control",
                        description: "İdrar DOA analizi kontrol çözümü — Tip E",
                        descriptionEN: "Urine DOA analysis control solution — Type E",
                        details: "İdrarla ilaç analizi (DOA) testleri için kalite kontrol çözümü. Laboratuvar doğruluğunu ve tutarlılığını sağlamak amacıyla kullanılır.",
                        detailsEN: "Quality control solution for drug-of-abuse (DOA) urine analysis tests. Used to ensure laboratory accuracy and consistency.",
                        unit: "Paket / Pack",
                        categoryId: "forensic", isAvailable: true, imageSystemName: "cross.vial.fill"),
                Product(id: "f8",
                        name: "Surine F Control",
                        nameEN: "Surine F Control",
                        description: "İdrar DOA analizi kontrol çözümü — Tip F",
                        descriptionEN: "Urine DOA analysis control solution — Type F",
                        details: "İdrarla ilaç analizi (DOA) testleri için kalite kontrol çözümü. Laboratuvar doğruluğunu ve tutarlılığını sağlamak amacıyla kullanılır.",
                        detailsEN: "Quality control solution for drug-of-abuse (DOA) urine analysis tests. Used to ensure laboratory accuracy and consistency.",
                        unit: "Paket / Pack",
                        categoryId: "forensic", isAvailable: true, imageSystemName: "cross.vial.fill"),
                Product(id: "f9",
                        name: "Surine In-House DOA",
                        nameEN: "Surine In-House DOA",
                        description: "Kurum içi DOA test kontrol çözümü",
                        descriptionEN: "In-house DOA test control solution",
                        details: "Kurum içi ilaç tarama programları için özel olarak geliştirilmiş kontrol çözümü. Güvenilir ve tekrarlanabilir sonuçlar için optimize edilmiştir.",
                        detailsEN: "Control solution specially developed for in-house drug screening programmes. Optimised for reliable and reproducible results.",
                        unit: "Paket / Pack",
                        categoryId: "forensic", isAvailable: true, imageSystemName: "cross.vial.fill"),
                Product(id: "f10",
                        name: "Surine Negative Control",
                        nameEN: "Surine Negative Control",
                        description: "DOA negatif kontrol çözümü",
                        descriptionEN: "DOA negative control solution",
                        details: "İlaç analizi testlerinde negatif referans olarak kullanılan kontrol çözümü. Test sisteminin doğru kalibrasyonu için kritik öneme sahiptir.",
                        detailsEN: "Control solution used as a negative reference in drug analysis tests. Critical for the correct calibration of the test system.",
                        unit: "Paket / Pack",
                        categoryId: "forensic", isAvailable: true, imageSystemName: "cross.vial.fill"),
                Product(id: "f11",
                        name: "Surine Preservative Free Control",
                        nameEN: "Surine Preservative Free Control",
                        description: "Koruyucu içermeyen DOA kontrol çözümü",
                        descriptionEN: "Preservative-free DOA control solution",
                        details: "Koruyucu madde içermeyen özel formülasyon. Koruyucu madde girişiminin söz konusu olduğu hassas DOA analizleri için idealdir.",
                        detailsEN: "Special formulation containing no preservatives. Ideal for sensitive DOA analyses where preservative interference may be a concern.",
                        unit: "Paket / Pack",
                        categoryId: "forensic", isAvailable: true, imageSystemName: "cross.vial.fill"),
            ],
            imageName: "forensic_category"
        )

        // MARK: - İhracat Ürünleri / Export Products
        let export = Category(
            id: "export",
            name: "İhracat Ürünleri",
            nameEN: "Export Products",
            icon: "🌍",
            colorHex: "1A5276",
            products: [
                Product(id: "e1",
                        name: "İhracat Ürünleri",
                        nameEN: "Export Products",
                        description: "Uluslararası ihracat ürünleri için bizimle iletişime geçin",
                        descriptionEN: "Contact us for international export products",
                        details: "Mensis Pharma'nın ihracat ürün kataloğu hakkında detaylı bilgi almak için lütfen bizimle iletişime geçiniz. Özel fiyatlandırma ve teslimat koşulları için ticari ekibimiz size yardımcı olacaktır.",
                        detailsEN: "Please contact us for detailed information about Mensis Pharma's export product catalogue. Our commercial team will assist you with special pricing and delivery terms.",
                        unit: "İletişime Geçin / Contact Us",
                        categoryId: "export", isAvailable: true, imageSystemName: "shippingbox.fill"),
            ],
            imageName: "export_category"
        )

        categories = [krillOil, vitamins, immune, forensic, export]
    }
}
